In [18]:
import pandas as pd
import numpy as np

dates1 = pd.date_range(start='2026-01-01', end='2026-1-31', freq='D').to_series().sample(5).sort_values()
dates2 = pd.date_range(start='2025-04-01', end='2025-4-30', freq='D').to_series().sample(3).sort_values()

order_id1 = np.random.randint(10000, 49999 + 1, size=5)
order_id2 = np.random.randint(50000, 99999 + 1, size=3)

products = ['A', 'B', 'C', 'D', 'E']
product1 = np.random.choice(products, size=5)
product2 = np.random.choice(products, size=3)

money1 = np.random.randint(100, 1000 + 1, size=5)
money2 = np.random.randint(100, 1000 + 1, size=3)

df1 = pd.DataFrame({'date': dates1, 'order_id': order_id1, 'product': product1, 'money': money1})
df2 = pd.DataFrame({'date': dates2, 'order_id': order_id2, 'product': product2, 'money': money2})

In [25]:
df1

                 date  order_id product  money
2026-01-02 2026-01-02     36895       C    805
2026-01-11 2026-01-11     27869       B    581
2026-01-12 2026-01-12     22242       B    848
2026-01-16 2026-01-16     20543       C    457
2026-01-17 2026-01-17     17508       D    900

In [27]:
df2

                 date  order_id product  money
2025-04-10 2025-04-10     89026       A    414
2025-04-16 2025-04-16     76632       E    537
2025-04-21 2025-04-21     91185       D    110

In [28]:
pd.concat([df1, df2])

                 date  order_id product  money
2026-01-02 2026-01-02     36895       C    805
2026-01-11 2026-01-11     27869       B    581
2026-01-12 2026-01-12     22242       B    848
2026-01-16 2026-01-16     20543       C    457
2026-01-17 2026-01-17     17508       D    900
2025-04-10 2025-04-10     89026       A    414
2025-04-16 2025-04-16     76632       E    537
2025-04-21 2025-04-21     91185       D    110

In [33]:
df1 = pd.DataFrame({"苹果": [88, 99, 92], "香蕉": [70, 90, 95], }, index=["1月", "2月", "3月"])
df2 = pd.DataFrame({"山竹": [88, 99, 92], "西瓜": [70, 90, 95], }, index=["1月", "2月", "3月"])

In [34]:
df1

    苹果  香蕉
1月  88  70
2月  99  90
3月  92  95

In [35]:
df2

    山竹  西瓜
1月  88  70
2月  99  90
3月  92  95

In [37]:
df1.join(df2, how='outer')

    苹果  香蕉  山竹  西瓜
1月  88  70  88  70
2月  99  90  99  90
3月  92  95  92  95

In [43]:
pd.merge(df1, df2, left_index=True, right_index=True, how='outer')

    苹果  香蕉  山竹  西瓜
1月  88  70  88  70
2月  99  90  99  90
3月  92  95  92  95

In [50]:
sdata = np.random.randint(0, 100 + 1, size=100)
sdata

array([ 44,  38,  52,  20,  71,  67,  43,  33,  13,   1,  70,  25,  26,
        96,   6,  83,  18,  79,  16,  56,  92,  77,  99,  58,  22,  54,
        21,  42,  93,  24,  15,  95,  40,   9,  66,  14,  90, 100,  69,
        73,  51,  75,  42,  91, 100,  39,  53,  11,  10,  87,  86,  44,
        67,  88,  53,  46,  37,  85,  57,  58, 100,  89,  80,  85,  64,
        76,  98,  88,  23,  57,  60,   7,  16,  91,  38,  22,  51,  89,
        59,  25,  66,  69,  94,   6,  43,  28,  12,  36,  24,  87,  38,
        47,  27,  16,  29,  44,  84,  78,  87,  95])

In [65]:
r = pd.cut(sdata, [60, 80, 100], right=False)
r.value_counts()

[60, 80)     16
[80, 100)    24
Name: count, dtype: int64

In [69]:
pdata = pd.DataFrame({"订单ID": [1, 2, 3, 4, 5], "渠道": ["A", "B", "C", "D", "A"], "销量": [100, 200, 300, 400, 500],
                      "销售金额": [1000, 2000, 3000, 4000, 5000]})

pdata.groupby("渠道")["销量"].sum()

渠道
A    600
B    200
C    300
D    400
Name: 销量, dtype: int64

In [70]:
df = pd.DataFrame([ ["张三", "abcd1234"], ["李四", "a2b4c3r5"]], columns=["name", "pwd"])
df

  name       pwd
0   张三  abcd1234
1   李四  a2b4c3r5

In [96]:
df.pwd.replace(r"\d", "*", regex=True)
df

  name       pwd
0   张三  abcd1234
1   李四  a2b4c3r5