In [2]:
import pandas as pd

pd.DataFrame([["p_2222", "u_dddd"]], columns=['p', 'u'])

        p       u
0  p_2222  u_dddd

In [9]:
df = pd.DataFrame({"苹果": [88, 99, 92], "香蕉": [70, 90, 95]}, index=['1月', '2月', '3月'])
df[df['香蕉'] > 90]

    苹果  香蕉
3月  92  95

In [10]:
df['香蕉'].sum()

np.int64(255)

In [15]:
df.sum()["香蕉"]

np.int64(255)

In [16]:
df['香蕉'].count()

np.int64(3)

In [18]:
df.count()

苹果    3
香蕉    3
dtype: int64